# -*- coding: utf-8 -*-
"""Scrape company name.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zCrb1LJqYA9FVi5F6XzSvrUOA-joCylp
"""

from bs4 import BeautifulSoup
import requests
import warnings
warnings.filterwarnings("ignore")

url = input('Please enter URL to Scrape for Company Name   ')
def main():

    r = requests.get(url, verify=False)
    soup = BeautifulSoup(r.content, "html.parser")

    title = soup.title.string

    print('Company Name Is :', title)

    meta = soup.find_all('meta')

    for tag in meta:
        if 'name' in tag.attrs.keys() and tag.attrs['name'].strip().lower() in ['Description', 'Keywords']:
            print(tag.attrs['name'].lower())
            print(tag.attrs['content'])
    r#eturn title

if __name__ == '__main__':
    main()

